### PR TITLE
Required enhancement for Git::Status

### PR DESCRIPTION
**Pull request by antis81**
Small followup for PR #12.

### CODE REVIEW

**Comment by scunz** [comment]
This is looking good to me.

**Comment by antis81** [comment]
Good, I'll merge then.

**Comment by scunz** [comment]
Not sure if this should have  waited for the consumer code to change along. But at least there is no compiler errors...

**Comment by antis81** [comment]
Yeah, I new that before and it is a very small non-destructive change, that's why :smile:.

**Pull request merged**
