### PR TITLE
get the name prefix of a git reference

### PR DESCRIPTION
**Pull request by antis81**

### CODE REVIEW

**Comment by scunz** [comment]
_Ping_

I think, you wanted this for the References code and forgot to adjust the code to it, right? This is looking good. Just get it in :-)

**Comment by antis81** [comment]
Yeah, right - two things:
1. The code currently doesn't use this -> not breaking anything
2. The reason for that is, that this won't work correctly on remote refs and still "forgets" part of the prefix - but this is another problem to be solved later on :).

**Comment by scunz** [comment]
I might help defining exactly what the "prefix" is. I don't think git itself has that term. But it's still nice to have this... :-)

**Comment by antis81** [comment]
Ok, so I'll delete this branch also to make room for new ideas :).

**Pull request merged**
