### PR TITLE
Add a reference name analyzer

### PR DESCRIPTION
**Pull request by scunz**
Adding an analyzer for reference names.

### CODE REVIEW

**Comment by scunz** [comment]
@antis81, I think this is implemented and covered with suitable tests now. There's also a "tiny" class documentation. Given that docs, do you think we should sub-document all of the methods?

**Comment by antis81** [comment]
@scunz Yes, I also looked over this and everything looks good. Although the `cond ? a, b: false;` syntax gave me some trouble in understanding :smile:. But you just overloaded the ',' operator right?

> Given that docs, do you think we should sub-document all of the methods?

Think this is good as is.

**Comment by antis81** [comment]
Btw.: As currently not used, we can safely remove the `prefix` method and replace it with this approach. I see no reason in keeping it. When it is merged, I can adjust the rename dialog to this.

**Comment by scunz** [comment]
> But you just overloaded the ',' operator right?

Uhm, well no, I'm actually just "using" it. Thus, it's more that `return a ? b, c : d;` is like:

``` c++
if (a) {
    b;
    return c;
}
else {
    return d;
}
```

**Comment by scunz** [comment]
So, I'm getting this in... Wrt. prefix() method, you cannot simply replace it with this code. This code has no way to give you everything that is before the "scope".

**Comment by antis81** [comment]
Thanks for explaining the comma operator. I didn't know that, but assumed exactly what you wrote.

> Wrt. prefix() method, you cannot simply replace it with this code. This code has no way to give you everything that is before the "scope".

What I mean: The `prefix` method is actually dead code at the moment and I'd rather use the `RefNameAnalyzer` instead. In addition, in case of a namespace I am not sure what prefix returns. In case of a remote it returns `refs/remotes`, but we need `refs/remotes/origin`.

**Comment by scunz** [comment]
> I didn't know that, but assumed exactly what you wrote.

Yeah, it is one more totally useless language feature of C++ that I have finally found a viable use case for - after dealing with C++ for at least 20 years ^^

> What I mean: The prefix method is actually dead code at the moment and I'd rather use the RefNameAnalyzer instead. In addition, in case of a namespace I am not sure what prefix returns. In case of a remote it returns refs/remotes, but we need refs/remotes/origin.

Now, that you're saying it _that clear_, I tend to agree with you. I actually had more faith in it; but you're obviously right. So we should get rid of it (again) and add this feature to the `RefName` class.

I'd say: Let's define it with 2 new functions as:
-   `localName()`
  - returns empty string if neither isBranch() nor isTag() returns `true` else
  - returns scopeName() + '/' + name() if isScope() returns `true` else
  - returns name()
  - as a hint: After this, branchName() and tagName() can be simplified to "return empty or localName() if isXXX returns true"; XXX being Tag or Branch.
-    `fullName()`
  - Just for completeness: returns the FQRN as set in the constructor.
-   `scopePrefix()`
  - returns fullName() with the localName() removed.
  - NOTE: Contrary to other getters in `RefName` this includes a trailing slash unless the slash would be the only character.

The only difference in the implementation of scopePrefix() vs. Reference::prefix() would be that we can now better determine what scope() is. Do you want to setup a PR for that change or should I do so?

**Comment by antis81** [comment]
> The only difference in the implementation of scopePrefix() vs. Reference::prefix() would be that we can now better determine what scope() is. Do you want to setup a PR for that change or should I do so?

Please - if you don't mind - feel free to implement these last three methods also. Thanks in advance :heart:.

**Comment by scunz** [comment]
No problem, I will add those then.

**Pull request merged**
