### PR TITLE
sc/branchery

### PR DESCRIPTION
**Pull request by antis81**
Improvements to the Branch-API.

### CODE REVIEW

**Comment by antis81** [comment]
@scunz Anything against merging this branch? I became a "fan" of merging small changes instead of doing big things. Neither you nor I have the time to accomplish this and it is very frustrating to wait for implementations for weeks or even months. Instead I'd like to do the small steps required to slowly improve.

Btw.: I don't care, if you like to re-add the "VOID" macros. Also I'll never :heart: them.

**Comment by scunz** [comment]
@antis81 Added my local commits and rebased to master. Feel free to merge as is or complain :)

**Comment by scunz** [comment]
But wait a moment. I'll move 964a5b to a different PR.

**Comment by scunz** [comment]
Think it's ready now :100:

**Pull request merged**
