### PR TITLE
RefLog implementation

### PR DESCRIPTION
**Pull request by scunz**
This is lingering around locally. Let's get it in GH at least...

### CODE REVIEW

**Comment by antis81** [comment]
If you ask me, I'd put the visualization part into an MGV future version :). But it is good to have it here.

**Comment by scunz** [comment]
Actually, I need _all_ git core concepts implemented inside `libGitWrap` in order to create succeeding tests in the new RepoMan code... You'll probably see that soon ^^

**Comment by antis81** [comment]
:zap: Revived PR and rebased Branch.

**Comment by antis81** [comment]
:100: Completed implementation! @scunz Could you check this, please? I introduced inheritance from our `RepoObject` and `Base`.

DONE!! ~~Note: Forgot the `RefLog::write()` method. Implementing it now :smile:.~~

**Comment by antis81** [comment]
I'll merge here. Feel free to review and comment or open a new PR.

**Pull request merged**
